-- KAY GUITAR · Pedidos, productos y comprobantes
-- Ejecuta este archivo COMPLETO una sola vez en Supabase:
-- SQL Editor > New query > pega el contenido > Run.
-- No contiene claves privadas.

create extension if not exists pgcrypto;

-- Catálogo que utiliza el servidor. Los precios que llegan desde el navegador
-- nunca se aceptan como fuente de verdad.
create table if not exists public.store_products (
  id text primary key,
  name text not null,
  price_mxn integer not null check (price_mxn >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.store_products (id, name, price_mxn) values
  ('clean-amb-od', 'Clean Amb OD', 50),
  ('clean-chorus', 'Clean Chorus', 50),
  ('clean-punch', 'Clean Punch', 50),
  ('victoria-averly-morillo', 'Victoria — Averly Morillo', 50),
  ('preset-regalo', 'Preset de regalo', 0),
  ('pack-ac30-carol-jc', 'AC30 • Carol Ann • JC', 300),
  ('essential-tone-pack', 'Essential Tone Pack', 120)
on conflict (id) do update set
  name = excluded.name,
  price_mxn = excluded.price_mxn,
  updated_at = now();

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity (start with 1001) unique not null,
  order_code text unique,
  user_id uuid not null references auth.users(id) on delete restrict,
  customer_email text not null,
  customer_name text not null,
  items jsonb not null check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) > 0),
  total_mxn integer not null check (total_mxn >= 0),
  payment_method text not null check (payment_method in ('bank_transfer', 'paypal')),
  status text not null default 'pending_payment' check (status in (
    'pending_payment',
    'pending_validation',
    'payment_approved',
    'payment_rejected',
    'cancelled',
    'delivered'
  )),
  receipt_path text,
  paypal_order_id text unique,
  paypal_capture_id text,
  checkout_token uuid unique,
  download_links jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz,
  delivered_at timestamptz
);

-- Bitácora interna para que un doble clic o reintento no mande correos duplicados.
create table if not exists public.order_notifications (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  event text not null check (event in ('bank_receipt', 'paypal_approved')),
  sent_at timestamptz not null default now(),
  unique (order_id, event)
);

-- Convierte el número interno en el código visible del cliente: PED-1001.
create or replace function public.set_order_code()
returns trigger
language plpgsql
as $$
begin
  if new.order_code is null then
    new.order_code := 'PED-' || lpad(new.order_number::text, 4, '0');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_order_code_before_insert on public.orders;
create trigger set_order_code_before_insert
before insert or update on public.orders
for each row execute procedure public.set_order_code();

create index if not exists orders_user_created_idx on public.orders (user_id, created_at desc);
create index if not exists orders_status_created_idx on public.orders (status, created_at desc);

alter table public.store_products enable row level security;
alter table public.orders enable row level security;
alter table public.order_notifications enable row level security;

drop policy if exists "Products are visible to everyone" on public.store_products;
create policy "Products are visible to everyone"
on public.store_products for select
to anon, authenticated
using (active = true);

-- Cada cliente sólo puede ver sus propios pedidos. No hay políticas de insertar,
-- modificar o borrar desde el navegador: eso se realiza con funciones controladas.
drop policy if exists "Users can read their own orders" on public.orders;
create policy "Users can read their own orders"
on public.orders for select
to authenticated
using (auth.uid() = user_id);

-- Arquitectura preparada para un panel futuro: asigna app_metadata.role = admin
-- desde un entorno seguro antes de mostrarle dicho panel a una persona.
create or replace function public.is_store_admin()
returns boolean
language sql
stable
as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false);
$$;

drop policy if exists "Admins can manage orders" on public.orders;
create policy "Admins can manage orders"
on public.orders for all
to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

-- El bucket es privado. Sólo el dueño de un pedido puede subir y consultar
-- archivos dentro de su propia carpeta: user-id/order-id/archivo.ext
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'payment-receipts',
  'payment-receipts',
  false,
  10485760,
  array['application/pdf', 'image/png', 'image/jpeg']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Customers upload their own receipts" on storage.objects;
create policy "Customers upload their own receipts"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'payment-receipts'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Customers read their own receipts" on storage.objects;
create policy "Customers read their own receipts"
on storage.objects for select
to authenticated
using (
  bucket_id = 'payment-receipts'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- Crea un pedido de forma segura. El servidor vuelve a calcular artículos,
-- cantidades y total desde store_products, y el token evita duplicados por doble clic.
create or replace function public.create_store_order(
  p_items jsonb,
  p_payment_method text,
  p_checkout_token uuid default null
)
returns table (
  id uuid,
  order_code text,
  total_mxn integer,
  status text
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_input_count integer;
  v_match_count integer;
  v_items jsonb;
  v_total integer;
  v_email text;
  v_name text;
  v_order public.orders%rowtype;
begin
  if v_user_id is null then
    raise exception 'Debes iniciar sesión para crear un pedido.' using errcode = '42501';
  end if;

  if p_payment_method not in ('bank_transfer', 'paypal') then
    raise exception 'Método de pago no permitido.' using errcode = '22023';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'El carrito está vacío.' using errcode = '22023';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_items) as input(product_id text, quantity integer)
    where input.product_id is null or input.quantity is null or input.quantity < 1 or input.quantity > 10
  ) then
    raise exception 'La cantidad de un producto no es válida.' using errcode = '22023';
  end if;

  if exists (
    with requested as (
      select product_id, sum(quantity)::integer as quantity
      from jsonb_to_recordset(p_items) as input(product_id text, quantity integer)
      group by product_id
    ) select 1 from requested where quantity > 10
  ) then
    raise exception 'No puedes comprar más de 10 unidades del mismo producto.' using errcode = '22023';
  end if;

  -- Si un clic se reintenta por conexión lenta, devuelve el mismo pedido.
  if p_checkout_token is not null then
    select * into v_order
    from public.orders
    where user_id = v_user_id and checkout_token = p_checkout_token;
    if found then
      return query select v_order.id, v_order.order_code, v_order.total_mxn, v_order.status;
      return;
    end if;
  end if;

  with requested as (
    select product_id, sum(quantity)::integer as quantity
    from jsonb_to_recordset(p_items) as input(product_id text, quantity integer)
    group by product_id
  )
  select count(*) into v_input_count from requested;

  with requested as (
    select product_id, sum(quantity)::integer as quantity
    from jsonb_to_recordset(p_items) as input(product_id text, quantity integer)
    group by product_id
  )
  select count(*) into v_match_count
  from requested r
  join public.store_products p on p.id = r.product_id and p.active = true;

  if v_input_count <> v_match_count then
    raise exception 'Uno o más productos ya no están disponibles.' using errcode = '22023';
  end if;

  with requested as (
    select product_id, sum(quantity)::integer as quantity
    from jsonb_to_recordset(p_items) as input(product_id text, quantity integer)
    group by product_id
  )
  select
    jsonb_agg(
      jsonb_build_object(
        'product_id', p.id,
        'name', p.name,
        'unit_price_mxn', p.price_mxn,
        'quantity', r.quantity,
        'line_total_mxn', p.price_mxn * r.quantity
      ) order by p.name
    ),
    sum(p.price_mxn * r.quantity)::integer
  into v_items, v_total
  from requested r
  join public.store_products p on p.id = r.product_id and p.active = true;

  select email into v_email from auth.users where id = v_user_id;
  select username into v_name from public.profiles where id = v_user_id;
  v_name := coalesce(v_name, split_part(coalesce(v_email, 'cliente'), '@', 1));

  insert into public.orders (
    user_id, customer_email, customer_name, items, total_mxn,
    payment_method, status, checkout_token
  ) values (
    v_user_id, coalesce(v_email, ''), v_name, v_items, v_total,
    p_payment_method, 'pending_payment', p_checkout_token
  ) returning * into v_order;

  return query select v_order.id, v_order.order_code, v_order.total_mxn, v_order.status;
end;
$$;

grant execute on function public.create_store_order(jsonb, text, uuid) to authenticated;

-- Guarda la ruta del comprobante y cambia únicamente el pedido propio de
-- pendiente de pago a pendiente de validación.
create or replace function public.submit_bank_receipt(
  p_order_id uuid,
  p_receipt_path text
)
returns table (
  id uuid,
  order_code text,
  status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_order public.orders%rowtype;
begin
  if v_user_id is null then
    raise exception 'Debes iniciar sesión.' using errcode = '42501';
  end if;

  if p_receipt_path is null
    or p_receipt_path !~ ('^' || v_user_id::text || '/' || p_order_id::text || '/') then
    raise exception 'La ruta del comprobante no es válida.' using errcode = '22023';
  end if;

  update public.orders
  set receipt_path = p_receipt_path,
      status = 'pending_validation',
      updated_at = now()
  where id = p_order_id
    and user_id = v_user_id
    and payment_method = 'bank_transfer'
    and status = 'pending_payment'
  returning * into v_order;

  if not found then
    raise exception 'Este pedido no puede recibir un comprobante.' using errcode = '22023';
  end if;

  return query select v_order.id, v_order.order_code, v_order.status;
end;
$$;

grant execute on function public.submit_bank_receipt(uuid, text) to authenticated;

-- Sólo lectura para el cliente, además de los RPC seguros de arriba.
grant select on public.store_products to anon, authenticated;
grant select on public.orders to authenticated;
